name: portabase-agent-b

services:

  app:
    container_name: portabase-agent
    image: portabase/agent:latest
    restart: unless-stopped
    volumes:
      - ./databases.json:/config/config.json
    environment:
      LOG: info
      TZ: "UTC"
      POLLING: 5
      DATA_PATH: "/data"
      EDGE_KEY: "${EDGE_KEY}"
    networks:
      - portabase

networks:
  portabase:
    name: portabase
    external: true