apiVersion: v1
kind: Secret
metadata:
  name: portabase-env
  namespace: poc-portabase
type: Opaque
stringData:
  PROJECT_SECRET: "autopoc-secret-key-2026-portabase"
  AUTH_DEFAULT_USER: "admin@poc.example.com"
  AUTH_DEFAULT_PASSWORD: "PoCAdmin2026!"
  AUTH_DEFAULT_USER_NAME: "PoC Admin"
