apiVersion: v1
kind: Service
metadata:
  name: portabase-app
  namespace: poc-portabase
  labels:
    app: portabase
spec:
  selector:
    app: portabase
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
